FROM python:2.7

RUN pip install --upgrade pip
RUN pip install Flask==1.0.2
RUN pip install Flask-Cors==3.0.7
RUN pip install flask-sqlalchemy
RUN pip install psycopg2

COPY ./server /server

WORKDIR /server

ENTRYPOINT ["python"]

CMD ["main.py"]
